---
kind: deployment
apiVersion: apps/v1
metadata:
    name: nginx
    namespace: default
    labels:
        app: nginx
spec:
    replicas: 1
    selector:
        matchLabels:
            app: nginx
    template:
        metadata:
            labels:
                app: nginx
        spec:
            containers:
                - name: nginx
                  image: nginx:latest
                  ports:
                      - containerPort: 80
                  volumeMounts:
                      - name: nginx-config-volume
                        mountPath: /etc/nginx/conf.d
                        readOnly: true
                  resources:
                      requests:
                          memory: "64Mi"
                          cpu: "250m"
                      limits:
                          memory: "128Mi"
                          cpu: "500m"
            volumes:
                - name: nginx-config-volume
                  configMap:
                      name: nginx-config
                      items:
                          - key: default.conf

kind: configMap
apiVersion: apps/v1
metadata:
    name: nginx-config
    namespace: default
    labels:
        app: nginx
data:
    default.conf: |
        server {
            listen 80;
            server_name localhost;

            location / {
                root   /usr/share/nginx/html;
                index  index.html index.htm;
            }

            error_page 404 /404.html;
            location = /40x.html {
                internal;
            }

            error_page 500 502 503 504 /50x.html;
            location = /50x.html {
                internal;
            }
        }
