all:
  hosts:
    web1:
      ansible_host: 192.168.1.10
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/my-key.pem
    web2:
      ansible_host: 192.168.1.11
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/my-key.pem
  children:
    webservers:
      hosts:
        web1:
        web2:
    dbservers:
      hosts:
        db1:
          ansible_host: 192.168.1.12
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/my-key.pem
